<?php
include 'fpdf/fpdf.php';
include 'koneksi.php';
$date = new DateTime();
$tanggal = $date->format('Y-m-d H:i:s');
$pdf = new FPDF('L','mm',array(100,60));
$pdf->AddPage();
$pdf->SetFont('Arial','','10');
$pdf->Cell(80,9,'Nomor Antrian',0,1,'C');
$id = $_GET['id'];
$data = $conn->query("SELECT * FROM posyandu WHERE id=$id")->fetch_assoc();
$pdf->Cell(80,0,$data['nama'],0,1,'C');
$nama_posyandu = $data['nama'];
$nama_posyandu_nospace = str_replace(" ","",$nama_posyandu);
$alamat = $data['alamat'];
$connect = mysqli_connect('localhost', 'root', '', 'posyandu');
$query = mysqli_query($connect, "SELECT MAX(kode) as kode FROM peserta WHERE posyandu = '$nama_posyandu'");
$data = mysqli_fetch_array($query);
$kode_baru = $data['kode'];
$urutan = substr($kode_baru, 5, 3);
$urutan++;
// echo(sprintf('%05s',$urutan));
$huruf = substr($nama_posyandu_nospace,8,3).'-';
$kode_baru = $huruf . sprintf("%03s", $urutan);
$pdf->SetFont('Arial','B','20');
$pdf->Cell(80,10,$kode_baru,0,1,'C');

$pdf->SetFont('Arial','',8);
$pdf->Cell(80,0,$tanggal,0,1,'C');
$pdf->Cell(80,3,'',0,1,'C');
$pdf->SetFontSize(8);
$pdf->Cell(80,0,'Simpan nomor peserta dengan baik. Perlihatkan saat di Posyandu',0,1,'C');
// $pdf->Cell(80,10,' Perlihatkan saat di Posyandu',0,1,'C');
$pdf->SetFont('Arial','','6');
$pdf->Cell(80,7,'Harap datang ke '.$nama_posyandu.'('.$alamat.') tepat waktu',0,1,'C');
$pdf->SetFont('Arial','b','6');
$pdf->Cell(80,0,'Jika antrian terlewat, maka nomor tidak sah.',0,1,'C');
$conn->query("INSERT INTO peserta (kode,tanggal,posyandu) VALUES ('$kode_baru','$tanggal','$nama_posyandu')");
$pdf->Output();